version: "3.9"

services:
  backend:
    image: rajkrr/chat_app_backend:latest
    container_name: backend_c
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: rajkrr/chat_app_frontend:latest
    container_name: frontend_c
    ports:
      - "8080:80"
    restart: always
